### ISSUE TITLE
Menu Improvements + Providing Help to User

### ISSUE THREAD

**Issue by charlestian23** [Bram-Hub/Legup#103]
Some improvements for the current menu in Legup:

- [ ] Create a new `Help` menu
     - [ ] Create a `Legup Help` option that when clicked, shows dialog for how to navigate and use Legup
     - [ ] Create a `Puzzle Help` option that when clicked, shows dialog for how to solve the given puzzle
- [ ] Rename `Help Legup` in `About` menu to `Contribute to Legup`

**Comment by Chase-Grajeda** [comment]
Merged by https://github.com/Bram-Hub/Legup/pull/327
