### ISSUE TITLE
Zoom Window Bugs

### ISSUE THREAD

**Issue by Hiimadd** [Bram-Hub/Legup#114]
When using two-finger scrolling on a laptop, the window disappears instead of moving the scroll bar, additionally, using pinch zoom will zoom the window correctly, but not adjust the zoom bar on the bottom of the window
![TwoFingerScrollIssue](https://user-images.githubusercontent.com/25335008/172458927-c885542c-c694-446a-9ee6-76e9de0b0a31.JPG)
![PinchZoomIssue](https://user-images.githubusercontent.com/25335008/172458928-8d0e7b5c-5317-45bf-a007-f174e0a0549c.JPG)
.

To do:
- [x] Fix the window disappearing instead of moving the scroll bar bug
- [ ] Make zooming adjust the zoom bar on the bottom right

**Comment by Chase-Grajeda** [comment]
Reopening issue, the previous merge solves the touchpad not working, however the zoom bar does not update upon zoom
