### ISSUE TITLE
Puzzle Cell classes extend from GridCell as an integer

### ISSUE THREAD

**Issue by Corppet** [Bram-Hub/LEGUP#139]
All puzzles currently have their cell class extend from `GridCell` as `Integer` types, yet they have their own respective types/enums. It may be a good idea down the line to change each cell class to use their own respective classes instead, which also means changing `GridCell` and `PuzzleElement` to work with `enums`.

**For Example:**

Current:
```Java
public class TreeTentCell extends GridCell<Integer>
```

Suggestion:
```Java
public class TreeTentCell extends GridCell<TreeTentType>
```

**To do:**
- [x] Revise the `GridCell` and `PuzzleElement` classes to work with `enums`. If the codebase seems more suitable to use `Integer` instead of their respective types, please comment about it below and provide some short reasoning if you can. Alternatively, you can store the integer data value within the `enum` class instead of `GridCell` and have your code perform arithmetic on that instead.

Change the cast types for each cell class...
- [x] Battleship
- [x] Fillapix
- [x] Heyawake
- [x] Lightup
- [x] Masyu
- [x] Nurikabe
- [x] Short Truth Table
- [x] Skyscrapers
- [x] Sudoku
- [x] Tree Tent

**Comment by charlestian23** [comment]
Note that if any changes are made here, we should double check that this tutorial is still up to date: https://github.com/Bram-Hub/Legup/wiki/Implementing-Puzzles

**Comment by 25tallurich** [comment]
Im doing LightUp rn

**Comment by 25tallurich** [comment]
Ill also do Nurikabe

**Comment by Acewvrs** [comment]
I'll do sudoku

**Comment by pitbull51067** [comment]
I'll do Fillapix

**Comment by RyancRiv** [comment]
I can do Lightup

**Comment by RyancRiv** [comment]
I can do SkyScrapers

**Comment by RyancRiv** [comment]
I can do Skyscrapers

**Comment by ErinCohenGH** [comment]
I believe someone is already doing both of those

**Comment by Acewvrs** [comment]
I'll do heyawake now

**Comment by Acewvrs** [comment]
I'm doing short truth table

**Comment by pitbull51067** [comment]
I'll do Tree Tent

**Comment by Corppet** [comment]
I have already talked with some of you, but if you think the puzzle you are working on is using arithmetic with the `data` property in their respective `GridCell` and you think the generic type of the cell is better left as an `Integer`, please indicate so in a comment and provide some simple reason as to why.

**Comment by ErinCohenGH** [comment]
Nurikabe is also better left as an Integer because setting the type of cell is reliant on being able to set a numerical value in addition to just black or white.

**Comment by ErinCohenGH** [comment]
Is LightUp still being worked on?

**Comment by 25tallurich** [comment]
LightUp has the same issue as heyawake and Sudoku the code does math on the numbers so it is not viable to do.

**Comment by ErinCohenGH** [comment]
I'll do Short Truth Table then, thanks.
