### ISSUE TITLE
[BUG] Selecting a rule overlaps other rule tabs.

### ISSUE THREAD

**Issue by Corppet** [Bram-Hub/LEGUP#222]
### Description

While editing a proof, when the rule categories are on separate rows, selecting one of the tabs will overlap another.

### Steps to Reproduce

1. Legup --> Open Proof
2. Select a rule tab on the left

### Expected Behavior

Rule tabs should not overlap (probably don't change size when selected).

### Screenshots

![image](https://user-images.githubusercontent.com/41582274/181084442-7bd10857-2417-4f50-b705-92bd7575007f.png)

**Comment by jadeandtea** [comment]
The rule tabs were cleaned up at some point and now look fine. I am closing this for now.
