### ISSUE TITLE
[ENHANCEMENT] Verify the validity of the board before saving a puzzle file from the puzzle editor

### ISSUE THREAD

**Issue by charlestian23** [Bram-Hub/Legup#267]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

When testing the Tree Tent puzzle editor, I ran into this error when attempting to open one of the puzzle files I created:
```[ERROR] 2022-08-11 10:46:43.884 [AWT-EventQueue-0] ProofEditorPanel - InvalidFileFormatException: TreeTent Importer: there must be same number of clues as the dimension of the board```

This is not a problem with the puzzle editor, but a problem with the file I created. I did not know that the number of clue had to be the same as the dimension of the board. Legup does not provide any sort of indication that the file I created was bad, only that the file is invalid when I try to open it.

### Describe the improvement you'd like

Before saving the puzzle file, Legup should run a quick check for each puzzle to check whether or not the puzzle file is valid. If it is not valid, Legup should display a warning letting the user know that the file is not valid, and let them choose whether or not they would like to continue to proceed to save the file.

### Describe alternatives you've considered

The error message when opening a file could also be updated to state that the puzzle file Legup is attempting to open is breaks the rules of the puzzle. Maybe this feature could be implemented in conjunction with the improvement I've suggested above.

**Comment by Chase-Grajeda** [comment]
Fixed by #377
