### ISSUE TITLE
[FEATURE] Documentation for implementing the puzzle editor for a new puzzle

### ISSUE THREAD

**Issue by charlestian23** [Bram-Hub/LEGUP#269]
### Is your feature request related to a problem? Please describe.

Currently, there is no documentation for developers trying to implement the puzzle editor for a new puzzle. 

### Describe the solution you'd like

Some documentation for how the Nurikabe puzzle editor was implemented as a sample would be nice. Should be similar to the documentation here: https://github.com/Bram-Hub/Legup/wiki/Implementing-Puzzles

### Additional Context

Thanks to @HenryCullom on compiling a list of what needs to be done to support a new puzzle:
![image](https://user-images.githubusercontent.com/46334090/184219143-ee3b6c71-f99b-4971-8584-b797772fb880.png)

**Comment by VortiganOfficial** [comment]
I added the typed version of the discord messages in the tutorial, but I understand that the explanation probably needs pictures and better explanations
