### ISSUE TITLE
[ENHANCEMENT] Download Latest JRE in Installer

### ISSUE THREAD

**Issue by TrevorBrunette** [Bram-Hub/LEGUP#281]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

Currently, compiling the installer requires the packaging of a JRE from the distributor machine. The way it is currently programmed requires the user to have a certain version of Java installed in a certain directory. This results in needing to change the InnoSetup script depending on the user's system or install another JRE to the system when one already exists.

### Describe the improvement you'd like

It is possible to have the InnoSetup script download and install Java when run. This would be ideal since the installer would not need to be as large and these changes to the InnoSetup script would not need to be made when running on a machine where the path of the JRE or the installed JRE version is different.

### Describe alternatives you've considered

I have considered using a script to detect the JRE version closest to the desired one on the system, however this would lead to potentially unexpected issues in finding and shipping an incorrect JRE. I have also considered adding a compressed version of the correct JRE to the git repository, but that seems like an improper use of git since it would just be essentially hosting a read-only file.

**Comment by charlestian23** [comment]
Closed with #714
