### ISSUE TITLE
[ENHANCEMENT] Rules Section For Puzzles

### ISSUE THREAD

**Issue by 19690ao** [Bram-Hub/LEGUP#290]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

There's no place in the repo where the rules of each game are stored.

### Describe the improvement you'd like

Add a section to the wiki with the rules of each game.

**Comment by Bram28** [comment]
A bunch of puzzles and their rules are now in the Wiki.  Hopefully that'll make it clear to future developers to do the same for all other puzzles. ... closing this issue
