### ISSUE TITLE
"Fill in Black" not working

### ISSUE THREAD

**Issue by cjreed121** [Bram-Hub/Legup#30]
**Current Behavior**
When you have black and gray squares around a gray square, you can use the fill in black rule to claim that square should also be black. This is not valid reasoning as all squares must be black.

The following photo shows what the issue looks like. First a black square was placed to the left of the 6 using the Fill In Black rule which was clearly wrong. Next a black square was placed below using same rule except that was marked as valid when it does not make sense using the same rule.

![nurikabe_edit](https://user-images.githubusercontent.com/55092742/133708601-a743332f-2c14-41a7-bd14-0ac553f84997.png)

**Expected Behavior**
This rule should not be valid in cases like this. It must be that all 4 squares around a gray square are black in order for that gray square to be marked as black.

**Steps to reproduce**
1. Download and extract [Error File.zip](https://github.com/Bram-Hub/Legup/files/7181831/Error.File.zip)
2. Open the file in Legup
3. Inspect the current rules and board in those rules
4. You should see that the Fill In Black rule is marked as valid when it shouldn't be

**Comment by Chase-Grajeda** [comment]
Closing issue, bug fixed and merged
