### ISSUE TITLE
[BUG] `CannotReachCellBasic` Rule Ignores Board State

### ISSUE THREAD

**Issue by 19690ao** [Bram-Hub/Legup#300]
### Description

Nurikabe's `Can't Reach Cell` rule doesn't account for black squares and the existing white squares in the region.

### Steps to Reproduce

We have a nurikabe board like this one:
![image](https://user-images.githubusercontent.com/60408336/193352418-39fb83a7-87ba-4a57-8aa1-306d633115ec.png)
Attempt to make the following squares `black`:
![image](https://user-images.githubusercontent.com/60408336/193352712-6d6ceaa7-4cc1-4cfe-bf54-045e1af1bc37.png)
Some squares fail to check out, despite every white area being out of reach. 

### Expected Behavior

The black squares in the example should check out. The only reason they don't is that the program "thinks" the 6 can reach the cells, despite its region only having 3 more white cells to spare. 
`CannotReachCell` should be using a breadth-first search to determine if a black square can be reached by a region.

**Comment by Chase-Grajeda** [comment]
Closed by https://github.com/Bram-Hub/Legup/pull/321
