### ISSUE TITLE
[ENHANCEMENT] Implement Batch Grader Button

### ISSUE THREAD

**Issue by Chase-Grajeda** [Bram-Hub/Legup#301]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

Currently, the batch grader button does not utilize the pre-made function

### Describe the improvement you'd like

On the startup screen, have the batch grader work

**Comment by wei-jun7** [comment]
it should be fix now.

**Comment by Chase-Grajeda** [comment]
Fixed by #344
