### ISSUE TITLE
[ENHANCEMENT] <Main Menu Edit Button Directory>

### ISSUE THREAD

**Issue by Tripplenut** [Bram-Hub/Legup#310]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

Currently, on the main menu, when you click the solve puzzle button, the user is sent to either a default or custom directory. When you click the edit puzzle button, it goes to the default directory regardless. The visuals of both directories are also different. The goal is to alter the edit puzzle buttons to make it all consistent, and reveal the custom directory if given.

### Describe the improvement you'd like

The edit button will now use the users custom directory (if given) and both the solve and edit directories will look the same visually.

### Additional Context

A photo of the directory when you click the solve puzzle button
![Solve Puzzle](https://user-images.githubusercontent.com/67553651/193926981-ce76e729-3283-438a-a114-64b461f6e8c3.png)

The photo of the directory when you click the edit puzzle button
![edit puzzle](https://user-images.githubusercontent.com/67553651/193927126-4525e9dd-5614-4cb6-8c89-788e42b166cd.png)

**Comment by Chase-Grajeda** [comment]
https://github.com/Bram-Hub/Legup/pull/318
