### ISSUE TITLE
"No Number" not working

### ISSUE THREAD

**Issue by cjreed121** [Bram-Hub/Legup#32]
**Current Behavior**
There is a case where the contradiction No Number can incorrect be valid. An example is shown in the picture below.

![nurikabe](https://user-images.githubusercontent.com/55092742/133709773-45fbb77e-c1f7-4fd8-9220-1356c8f8c782.png)

This is assuming there is some white area that isn't a number surrounded by 4 black squares.

**Expected Behavior**
This should be invalid because there is no issue like that in the board.

**Steps to reproduce**
1. Download and extract [Error File.zip](https://github.com/Bram-Hub/Legup/files/7181946/Error.File.zip)
2. Open the file in Legup
3. Go all the way to the right in the TreePanel and see the last rule
4. You will see this is being marked as a valid rule when it should not be

**Comment by Chase-Grajeda** [comment]
Closing case, bug fixed, solution merged
