### ISSUE TITLE
[BUG] Scroll Zoom Soft-Locks At 28% And 56%

### ISSUE THREAD

**Issue by 19690ao** [Bram-Hub/Legup#328]
### Description

The scroll wheel doesn't allow you to zoom out past 28% or 56% unless you aggressively scroll out.

### Steps to Reproduce

1. Open any puzzle
2. Use either a scroll wheel or slide 2 fingers down on a trackpad to zoom into the puzzle as much as you can.
3. Zoom back out the same way.

### Expected Behavior

The zoom feature shouldn't be soft-locked at 28% and 56%. You should be able to zoom in and out freely without getting "stuck".

**Comment by Mbijur** [comment]
When I tried to test this issue in "Solve Puzzle", there was no soft-lock at 28%, but it was present at 56%.

**Comment by charlestian23** [comment]
Just tested this again, bug seems to be present but it's inconsistent.

**Comment by jadeandtea** [comment]
This has been fixed.
