### ISSUE TITLE
[BUG] <Editing a Puzzle's that don't have an edit funciton>

### ISSUE THREAD

**Issue by Tripplenut** [Bram-Hub/LEGUP#331]
### Description

Currently with the edit puzzle button you are able to open puzzle files that don't have an edit feature. This leaves you with a puzzle on the screen but no elements or no way to interact with it. Thus making it useless 

### Steps to Reproduce

1. Click on the edit puzzle button to open the file directory
2.  Open any puzzle under the ones that don't have an edit feature
      1. Fillipix
      2. Masyu
      3. Short Truth Table
      4. Skyscrapers
      5. Sudoku
3. See bug (No selectable elements) 

### Expected Behavior

Puzzles that have no elements should give an error and return you back to the file explorer so that you can choose a puzzle that lets you edit it.

### Screenshots

Picture of elements for a puzzle that has an editor (Lightup)
![image](https://user-images.githubusercontent.com/67553651/195200299-6f0522c4-c133-424b-8dcb-5365f403dfd1.png)

Picture of elements for a puzzle that does not have an editor (Masyu)
![image](https://user-images.githubusercontent.com/67553651/195200471-0f051c9f-f6e5-4a46-be15-bb6abc684cd4.png)
![image](https://user-images.githubusercontent.com/67553651/195200514-032e6956-5bb2-4210-acc7-93f5b6781c75.png)

### Additional Context

The thing that makes this bug annoying is most of the puzzles don't have file name extensions. Unless someone wants to implement this to make it easier to differentiate the different game files that would be sick but that come with its own set of problems.

**Comment by charlestian23** [comment]
I think the puzzle name is coded into the puzzle file. Here's an example of a Masyu puzzle file:
![image](https://user-images.githubusercontent.com/46334090/210094555-3e9194ce-1656-4a2c-b868-b93b5056f6f2.png)

We could potentially just do a check to see if the file is for a game that isn't implemented yet.

**Comment by Tripplenut** [comment]
I didn't even know that. That definitely helps solve the problem.
