### ISSUE TITLE
[BUG] <Puzzle Editer stop working>

### ISSUE THREAD

**Issue by BoZhiDeng** [Bram-Hub/LEGUP#343]
### Description

Cannot select the element in the puzzle editor. It should show all elements of the grid clicked in the element panel. 

### Steps to Reproduce

1. Run the program
2. Click "Edit Puzzle"
3. Select a puzzle file
4. Click any grid in the "LightUpView" panel
5. See error

### Expected Behavior

1. Run the program
2. Click "Edit Puzzle"
3. Select a puzzle file
4. Click any grid in the "LightUpView" panel
5. All elements of the grid selected should show in the elements panel

### Screenshots

<img width="443" alt="image" src="https://user-images.githubusercontent.com/106386075/197284785-edb13ded-429a-4f1a-8682-37f528a3fa91.png">

**Comment by wei-jun7** [comment]
niubee

**Comment by wei-jun7** [comment]
it maybe is not the ui problem which it is the  rule have something wrong with the panel, if you can you can go to check it out

**Comment by DavidColetta** [comment]
I do not fully understand what the bug is. Elements cannot be placed in lightup because the lightup puzzle editor is incomplete, as I have pointed out in issue #445. What exactly is meant by "All elements of the grid selected should show in the elements panel"?

**Comment by charlestian23** [comment]
Adding the Light Up tag to this issue since it seems to be an issue with the Light Up puzzle editor and not the puzzle editor in general

**Comment by charlestian23** [comment]
This issue was probably due to the puzzle editor for Light Up not being fully implemented. Closing this issue since it does not seem to be relevant anymore.
