### ISSUE TITLE
[BUG] NoSuchMethodException when creating new lightup puzzle

### ISSUE THREAD

**Issue by XyaoFeiFei** [Bram-Hub/Legup#357]
### Description

When solving lightup puzzles, upon start, the following error will throw to the console:
[ERROR] 2022-10-31 23:13:29.837 [AWT-EventQueue-0] Puzzle - Unable to find elements for LightUp
java.lang.NoSuchMethodException: edu.rpi.legup.puzzle.lightup.elements.NumberTile.<init>()

### Steps to Reproduce

1. Run the build
2. Click Solve Puzzle
3. Open lightup puzzle 7x7 Easy 69495
4. The error will generate in the console

### Expected Behavior

There should be no error to throw.

### Screenshots

<img width="719" alt="image" src="https://user-images.githubusercontent.com/44251254/199150604-8f238c39-8254-4e7d-80f1-941a3688d0dc.png">

**Comment by XyaoFeiFei** [comment]
Fixed by adding the method in NumberTile.java

**Comment by Chase-Grajeda** [comment]
Fixed by #373
