### ISSUE TITLE
"Build-Your-Own-Rule" feature

### ISSUE THREAD

**Issue by Gerzer** [Bram-Hub/Legup#37]
Thanks to @themanofcat for this suggestion

**Comment by Bram28** [comment]
Yeah, I've dreamed of a feature like that ...Ideally, you'd have some language to be able to define a rule ... and that language at the same time serves to check any application of that rule. Yikes: that seems really, really hard!! So again, low priority. This would seem to be a nice Master's Thesis for someone!
