### ISSUE TITLE
[ENHANCEMENT] Add Support for LightUp in Puzzle Creator

### ISSUE THREAD

**Issue by Chase-Grajeda** [Bram-Hub/LEGUP#372]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

Currently, we only have puzzle creation support for Nurikabe and TreeTent

### Describe the improvement you'd like

We would like to introduce puzzle creation support for LightUp. Since this has already been done twice, there should be a fair amount of reference code to assist.

The non-placeable elements should be:
- Black square
- Black square with number
- Yellow square (lit space)
- Gray square (unlit space)

The placeable elements should be:
- Lightbulb
- Dot (asserts no lightbulb can be in space)

Note, the dots should be able to overlap yellow spaces

### Additional Context

See the Nurikabe editor and TreeTent editor for examples

**Comment by charlestian23** [comment]
Closing due to #629
