### ISSUE TITLE
[BUG] Able to Change TreeTent Puzzle goals while solving it

### ISSUE THREAD

**Issue by shadowluigi27** [Bram-Hub/LEGUP#379]
### Description

When solving a Tree-Tent Puzzle, the user can edit the row and column numbers that determine the required amount of tents that are in each row and column. 

### Steps to Reproduce

1) Open a Tree Tent Puzzle In "Solve Puzzle" mode
2) Click on the numbers on the right and bottom sides of the board
3) Notice that you are able to change the numbers in the proof

### Expected Behavior

You should NOT be able to change the numbers  that determine the number of tents in a row/column

### Screenshots

![Legup TreeTent Issue](https://user-images.githubusercontent.com/72285616/202033773-6187450f-3650-40ce-8711-66d8f53ee4dd.gif)

### Puzzle Files

Any Tree Tent Puzzle File

### Additional Context
This is able to fool the proof checker

**Comment by wei-jun7** [comment]
it should be fine on the current dev
