### ISSUE TITLE
Change the UI for the Rules menu

### ISSUE THREAD

**Issue by charlestian23** [Bram-Hub/Legup#39]
Currently, in order to see the name of a rule, the user must hover their mouse over an icon, which makes it cumbersome to find a particular rule. A simple solution to this is to display the name of the rule under the icon, though a more difficult one would be to implement a search bar for the rules.

**Comment by Bram28** [comment]
Well, ideally the icon should tell the whole story ....   but I see what you mean, especially if you're looking at a powerpoint that does have the names of the rules.

A somewhat related issue: scrolling with the mouse through the rules menu goes at glacial pace (before global warming, that is) ...

**Comment by Chase-Grajeda** [comment]
Solved via adding labels to rules. See changes in #364
