### ISSUE TITLE
[ENHANCEMENT] Add dark mode

### ISSUE THREAD

**Issue by charlestian23** [Bram-Hub/LEGUP#404]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

Since we are starting to update the UI icons to be more modern, I felt that changing the overall UI feel of Legup (and not just the icons), would be suitable.

- [x] Implement FlatLaf look and feel
- [x] Implement the ability for the user to toggle between light mode and dark mode

### Describe the improvement you'd like

Consider using [FlatLaf](https://github.com/JFormDesigner/FlatLaf) in Legup to give it a more modern feel.

### Describe alternatives you've considered

We can consider looking into other open source options to improve UI.

**Comment by charlestian23** [comment]
Note that using Flatlaf may also allow us to implement dark mode and light mode

**Comment by N-Desmarais** [comment]
I added the dependency and changed the look in feel [here](https://github.com/N-Desmarais/Legup/tree/flatlaf-testing)

@charlestian23 please pull and give it a look see how you like it

**Comment by charlestian23** [comment]
> I added the dependency and changed the look & feel [here](https://github.com/N-Desmarais/Legup/tree/flatlaf-testing-dev)
> 
> @charlestian23 please pull and give it a look see how you like it

Open a pull request and I'll review it there

**Comment by N-Desmarais** [comment]
Ok you can check it out [here](https://github.com/Bram-Hub/LEGUP/pull/423), probably shouldn't make PRs for things that shouldn't be merged?

**Comment by charlestian23** [comment]
My apologies, I thought you meant it was ready to be reviewed. I marked your pull request as a draft, and you can mark it as ready for review when you’re done.

**Comment by N-Desmarais** [comment]
Well it is ready for review? It just replaces the legup look and feel with flatlaf. Probably don't want to merge it in unless you're happy with the 1:1 replacement

**Comment by charlestian23** [comment]
Oh the pull request won't automatically merge without my approval. You can create the pull request when you finish working on the issue, and I don't like the result I can always reject the merge.

**Comment by charlestian23** [comment]
@N-Desmarais Do you want to work on implementing a dark mode as well or were you interested in working on something else?

**Comment by N-Desmarais** [comment]
@charlestian23 FlatLightLaf -> FlatDarkLaf?

**Comment by charlestian23** [comment]
Yeah, but we'd also need to create an option in the menu for users to select whether they want dark mode or light mode. The software would then need to change depending on what is selected.
