### ISSUE TITLE
[BUG] Unable to open any problems

### ISSUE THREAD

**Issue by blargwargyarg** [Bram-Hub/Legup#411]
### Description

LEGUP unable to open xml files and opens blank.

### Steps to Reproduce

Not sure if this is reproducible due to being unable to open any other files to reproduce it
1.  Use the check solution button
2. Save the file
3. Load file; this now occurs with all other files as well, not just the initial file. Restarting LEGUP has no effect on this behavior.

### Expected Behavior

file opens with saved progress.

**Comment by charlestian23** [comment]
Closing due to misleading title. See #416.
