### ISSUE TITLE
[ENHANCEMENT] Rename "Basic Rules" to "Direct Rules"

### ISSUE THREAD

**Issue by charlestian23** [Bram-Hub/LEGUP#412]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

This is taken from a conversation with @Bram28:

"As pointed out so many times now, the 'Basic' rules are really not 'basic', but can often be derived from case and contradiction rules (which themselves are therefore more 'basic'.  I also note that in the Wiki documentation page it talks about 'Basic Rules' as the more 'informal' rules of the game as someone might explain the game to you or as they are listed on a website for that puzzle... so that's confusing too."

### Describe the improvement you'd like

We want to change "Basic Rules" to "Direct Rules". Again, from @Bram28, "I think the average user is more likely to understand that a 'direct' rule allows them to do stuff quickly and 'directly' (as opposed to doing something like case and contradiction rules which seem more 'indirect' way of proving things. (indeed, proof by contradiction, which is effectively a combination case/contradiction rule is sometimes called 'Indirect Proof')."

We would need to change the language of "Basic Rules" at the following spots:
- [x] Anywhere in the UI where rules are labeled as "Basic Rules"
- [x] Preferably refactoring files named as "Basic Rules" to "Direct Rules"
- [ ] Anywhere in the documentation where rules are labeled as "Basic Rules"

### Describe alternatives you've considered

We also considered renaming to "Forced Rules", but it might be a bit ambiguous as to whether that means the rule forces things on the board or if the rule is forced itself, given other rules.

**Comment by charlestian23** [comment]
Code has been refactored in #422. @VortiganOfficial you can close this issue when you finish updating the documentation.

**Comment by VortiganOfficial** [comment]
Fixed documentation
