### ISSUE TITLE
[BUG] Short Truth-Table: Applying Operator Case Rules leads to red transitions

### ISSUE THREAD

**Issue by Bram28** [Bram-Hub/LEGUP#413]
### Description

If you apply any of the case rules involving an operator, the cases are correctly generated, but the transitions are red.

### Steps to Reproduce

Open any short truth-table puzzle. Go to Case Rules, and select any of the rules involving an operator

### Expected Behavior

Transitions should be green ... application of the rule should check out.

### Screenshots

![image](https://user-images.githubusercontent.com/2414519/213240902-18e29f3e-4760-4e72-852e-c30f2f6b0bfe.png)

**Comment by charlestian23** [comment]
Seems to be a repeat of #73

**Comment by charlestian23** [comment]
Closing this issue since it seems to have arisen due to the fact that we were temporarily using an older version of LEGUP for our class.

**Comment by Bram28** [comment]
This problem is still there in the newest version of LEGUP. Reopening issue ...

**Comment by ThisMatt** [comment]
Encountered this while working on something else. Seems like the checkRuleRaw() of edu/rpi/legup/puzzle/shorttruthtable/rules/caserule/CaseRule_Generic.java marks a case invalid if the two cases modify different cells.

![image](https://github.com/Bram-Hub/LEGUP/assets/98851950/308e2e27-8413-4b07-b5e0-b61488e23ead)

**Comment by Chase-Grajeda** [comment]
Good catch, I'm currently rewriting the chewRuleRaw implementation for the generic case rule class. It's the source for the bug described on this issue. Working changes are still on my fork
