### ISSUE TITLE
[ENHANCEMENT] Short Truth-Table: Case Rule 'Atomic Case' should be renamed and have new icon

### ISSUE THREAD

**Issue by Bram28** [Bram-Hub/LEGUP#414]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

Both the name an icon of the 'Atomic Case' rule suggest that this rule can only applied to atomic claims like A or B or P or Q. However, the rule can be applied to *any* statement. Indeed, if you select that case rule you find that all 'open' squares (reflecting unknown truth-values of statements) turn blue ... and that is just as it should be ... but the name and the icon should reflect that as well.

### Describe the improvement you'd like

For the name ... maybe 'True or False' will do it :)

For the icon: I have several ideas: 

1. We could replace the big fat P replaced either with a big fat Greek symbol Phi (which is what we typically use in logic as a statement variable that denotes any statement, atomic complex).  Not sure if all users intuitively understand that though ... a greek latter still looks like a letter .. and thus like an atomic statement.

2. Maybe we show a generic letter (and P is fine) as well as a generic operator in a square (with diagonal slash between them). Drawback there is that operator specific case rule also show operator

3. We can just show a completely empty cell and either have that be green and red with a slash  ... or do it like the Nurikabe rule with one arrow going from white cell to red cell and another from white cell to it being green.  Indeed, isn;t this how we have been iconizing most Case rules now?  With arrows?

### Describe alternatives you've considered

See above

### Additional Context

![image](https://user-images.githubusercontent.com/2414519/213244443-041cc543-b823-4a9f-aa06-e3d26e20e81a.png)

**Comment by charlestian23** [comment]
@VortiganOfficial Merged the pull request, you can change the documentation and close the issue once you're done with it.

**Comment by VortiganOfficial** [comment]
Changed atomic rule in documentation
