### ISSUE TITLE
[BUG] Modifying further cells in earlier transition does not make them unmodifable later on.

### ISSUE THREAD

**Issue by Bram28** [Bram-Hub/LEGUP#415]
### Description

If you go back to an earlier transition, you can indicate additional modifications to the board, which is good. However, those additional modified cells should become unmodifiable later on ... but you can modify them again.

### Steps to Reproduce

See successions of Screenshots berlow

### Expected Behavior

Again, see below

### Screenshots

Just take any LEGUP puzzle. For example, here is a LightUp puzzle:

![image](https://user-images.githubusercontent.com/2414519/213265284-6db412cc-6b61-4aa2-8db6-3befa8106bab.png)

We place a forced lightbulb:

![image](https://user-images.githubusercontent.com/2414519/213265469-5224dfdb-0e8a-4abd-9de1-83dfffe8e1b8.png)

Make another move:

![image](https://user-images.githubusercontent.com/2414519/213265569-9898811e-93bc-437b-acc0-227c65d6df9e.png)

We realize that we could have forced additional lightbulb during earlier transition with same rule:

![image](https://user-images.githubusercontent.com/2414519/213265769-abd20358-f3c5-4309-92f1-a696d5baa7de.png)

We return to end of branch .... the cell we just a lightbulb in should not be modifiable .. but we can! This is not good ... we should not be able to modify it once placed just like the other lightbulbs:

![image](https://user-images.githubusercontent.com/2414519/213266112-e94dd220-2d90-460f-962d-23f317a91691.png)

**Comment by N-Desmarais** [comment]
I was unable to recreate this bug on dev, following the provided steps using the same puzzle I got the following error:
![example](https://user-images.githubusercontent.com/55117352/215870722-6052a39f-17dc-427d-b636-7b3f20ce9ccb.png)

**Comment by N-Desmarais** [comment]
@Bram28 would you be willing to try this again on latest to ensure the problem persists?

**Comment by N-Desmarais** [comment]
@charlestian23 can you repro? if not lets close this one up

**Comment by Bram28** [comment]
Hey,  Just saw this ... I tried to recreate on the latest version I have
and indeed the problem is no longer there ... I must have been using an
older version. Sorry about that!!  :(
