### ISSUE TITLE
[BUG] Short Truth Table Biconditional Contradiction Not Being Read in Properly

### ISSUE THREAD

**Issue by charlestian23** [Bram-Hub/LEGUP#419]
### Description

When selecting the Biconditional Contradiction as part of a proof, after saving the file and reopening it, LEGUP changes the Biconditional Contradiction to the Contradicting Variable rule. This change is only reflected in the software; the XML file still states that the rule is the Biconditional Contradiction.

### Steps to Reproduce

1. Open the attached file
2. Notice that the incorrect contradictions are Contradicting Variable rules
3. Open the LEGUP file in Notepad or Notepad++
4. Notice that the final rule in the file is a Biconditional Contradiction

### Expected Behavior

The rule shown in the software should also be a Biconditional Contradiction

### Puzzle Files

[PropArg15.zip](https://github.com/Bram-Hub/Legup/files/10523263/PropArg15.zip)

**Comment by N-Desmarais** [comment]
Please note that all short truth table puzzle files affected need to be fixed by hand or re-generated
