### ISSUE TITLE
[ENHANCEMENT] "Exiting LEGUP?" table fix

### ISSUE THREAD

**Issue by pitbull51067** [Bram-Hub/LEGUP#424]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

When the "Exiting Legup?" table appears there are three options shown: "Yes", "No", and "Cancel". "No" and "Cancel" have the same meaning -- they don't make the program close.

### Describe the improvement you'd like

Remove the "cancel" button and just leave "Yes" and "No".

**Comment by VortiganOfficial** [comment]
I'm gonna TRY this, but I have very little experience with Java

**Comment by VortiganOfficial** [comment]
I tried, but I couldn't resolve the issue

**Comment by VortiganOfficial** [comment]
Removed the cancel option from all dialogue boxes because no and cancel mean the same thing in all contexts
