### ISSUE TITLE
Nurikabe White Bottleneck Rule Leads to Unsolvable Puzzle

### ISSUE THREAD

**Issue by eddiekrystowski** [Bram-Hub/Legup#43]
When working with the following puzzle
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Legup version="2.0.0">
    <puzzle name="Nurikabe">
        <board height="7" width="7">
            <cells>
                <cell value="1" x="3" y="0"/>
                <cell value="6" x="4" y="2"/>
                <cell value="2" x="6" y="2"/>
                <cell value="4" x="4" y="4"/>
                <cell value="3" x="6" y="4"/>
                <cell value="3" x="3" y="6"/>
            </cells>
        </board>
    </puzzle>
</Legup>
```

at this position 
![image](https://user-images.githubusercontent.com/28243927/135975908-ee3b53ca-a0a0-45e6-890a-61d036eec99a.png)

Applying the white bottleneck rule is considered "valid" for both
![image](https://user-images.githubusercontent.com/28243927/135975987-638a5625-ce4b-41d5-a160-c5a4850b4585.png)
and
![image](https://user-images.githubusercontent.com/28243927/135976020-29d3c973-6f88-4a2f-b6fe-c4d6c3f56a4b.png)

From the first position, it is possible to derive this position with valid steps:
![image](https://user-images.githubusercontent.com/28243927/135976196-9f9e9f02-893a-48d5-9c1d-654c1e1f66c4.png)

But as you can see, it is impossible to complete the puzzle in this state, thus I can contradict the whole thing

![image](https://user-images.githubusercontent.com/28243927/135976291-c802b205-654f-4856-a50f-f8b06442bbb6.png)

Even though this puzzle has a solution. The white bottleneck rule should probably not be applied to an ambiguous case such as this one where it can "escape" in multiple ways to avoid this false contradiction.

**Comment by Bram28** [comment]
Thanks @eddiekrystowski !  I had noticed this last week myself when checking the student submissions .... quite a few students ended up 'solving' the Nurikabe puzzle thanks to this bug. Grrrr!  

Now, just to be clear: the issue isn't so much that the puzzle becomes impossible to solve ... that's just a side-effect. The core issue is simply that the White Bottleneck rule has not been implemented correctly.  I've looked a little bit into its behavior, but can;t really figure out its thinking .. someone will just need to go to the code and hopefully be able to fix this.
