### ISSUE TITLE
[ENHANCEMENT] Cleaning up unused code

### ISSUE THREAD

**Issue by VortiganOfficial** [Bram-Hub/LEGUP#444]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

I was looking at the LegupUI.jar file and there is a function called showStatus which leads to nowhere but has a driver function that also is not used anywhere. Along with this, there are a bunch of functions that are not implemented. 

### Describe the improvement you'd like

Clean up unused/unimplemented functions so that the code is easier to read, navigate, and understand. Since I'm not super familiar with the code, I can't just go and delete anything as I please

**Comment by charlestian23** [comment]
Seems like this issue was resolved in #472. Closing this issue.
