### ISSUE TITLE
[BUG] When reloading STT, rules will incorrectly be marked red

### ISSUE THREAD

**Issue by DavidColetta** [Bram-Hub/LEGUP#465]
### Description

There seem to be many bugs with saving and reopening Short Truth Table files. This particular issue is that transitions that were previously green (justified) can sometimes become red (unjustified) after reloading a STT file.
I have a hunch this may be related to issue #138 

### Steps to Reproduce

1) Open a Short Truth Table puzzle.
2) Start solving it, get some green transitions
3) Save the puzzle
4) Reopen the puzzle
5) Observe that some of the green transitions have now turned red

### Expected Behavior

Transitions that are green before reloading file should remain green after reopening file.

### Screenshots

These transitions used to be all green before reloading.
![image](https://user-images.githubusercontent.com/67387813/219827576-b6406204-73ba-43b6-8d55-66ed865510ba.png)

**Comment by N-Desmarais** [comment]
Any chance we can get some more detailed steps to repro?

**Comment by sparakala21** [comment]
This issue is caused by the STT importer, it is likely connecting any subsequent root nodes to the root node. thats where i would start if i were working on this bug.

**Comment by sparakala21** [comment]
the red transitions are caused by the fact that the importer is not importing the nodes properly.
