### ISSUE TITLE
[BUG] open file dialogue boxes don't follow dark mode

### ISSUE THREAD

**Issue by VortiganOfficial** [Bram-Hub/LEGUP#475]
### Description

Pretty self explanatory. The only open file dialogue box that follows dark mode is in preferences > browse work directory and the batch grader box
The open file dialogue boxes for open and edit puzzles are different and only appear in white mode

### Steps to Reproduce

Dark mode boxes:
Preferences > Browse work directory 
Main Menu > batch grader

Light mode boxes:
Main Menu > Open puzzle
Main Menu > Edit puzzle

### Expected Behavior

dark mode = dark mode open file dialogue boxes

**Comment by charlestian23** [comment]
With the new FlatLaf updates, this seems to no longer be the case. Closing this issue.
