### ISSUE TITLE
[ENHANCEMENT] Logo Creation

### ISSUE THREAD

**Issue by 25tallurich** [Bram-Hub/LEGUP#477]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

We don't have a logo. Create a logo.

### Describe the improvement you'd like

Create Logo SVG. This is going to use for the merch and later on color it to look nice for the loading screen.

**Comment by VortiganOfficial** [comment]
We can also remember the darkmode setting and startup with the dark logo when starting the app
