### ISSUE TITLE
The Redo functionality should be implemented into the PuzzleEditor Panel

### ISSUE THREAD

**Issue by Mbijur** [Bram-Hub/LEGUP#478]
### Description

Right now, the redo function is empty in the PuzzleEditor Panel. If possible, the redo function in the PuzzleEditor Panel should mimic that in the ProofEditor Panel.

### Steps to Reproduce

 1. Check the ProofEditor Panel
 2. Find the redo functionality
 3. Implement a similar code in the PuzzleEditor Panel

### Expected Behavior

A redo function should be implemented to keep consistency between the PuzzleEditor Panel and the ProofEditor Panel.

### Screenshots

<img width="960" alt="Redo function" src="https://user-images.githubusercontent.com/122646363/221309459-1df67736-2a2d-4740-bc5d-ba09c7b74a75.png">

**Comment by charlestian23** [comment]
Closing since this seems to be a repeat of #288. However, the points mentioned in this issue can be a good starting point for those trying to tackle #288.
