### ISSUE TITLE
[BUG] Text for Invalid Use of Rules Overlapping with a Button

### ISSUE THREAD

**Issue by Acewvrs** [Bram-Hub/LEGUP#486]
### Description

The text that says "Invalid use of the rule . . ." overlaps with the resize button and the scroll bar if the window size is set to default.

### Steps to Reproduce

1. Open a short truth table file
2. Select any Direct Rule
3. Incorrectly apply the rule.
4. See the text "Invalid use of the rule [rule name]" appear on top of the resize board button.

### Expected Behavior

I expected the text to appear above or below the button so I can clearly see the text.

### Screenshots

<img width="256" alt="issue" src="https://user-images.githubusercontent.com/40209659/221993955-f8243768-e079-4dc5-bf55-47b83e11441d.png">

**Comment by Avilez-dev-11** [comment]
Issue could not be reproduced with the newest version on dev.
