### ISSUE TITLE
[ENHANCEMENT] TreeTent puzzle axis values.

### ISSUE THREAD

**Issue by walkingjason** [Bram-Hub/LEGUP#489]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

In a treetent puzzle, only the numbers on the right side should indicate how many tents are in the respective row. Currently, the same numbers are also used in the lower side.
![image](https://user-images.githubusercontent.com/29169987/222309437-206dd7ed-8605-486b-ab9e-63b9beb2fff6.png)

### Describe the improvement you'd like

The numbers on the lower side should reflect the coordinates, like the numbers on the top side.
![image](https://user-images.githubusercontent.com/29169987/222309607-df09bb12-eef3-45df-8aaa-d10be734acbd.png)

**Comment by Corppet** [comment]
Closing this because this does not seem to be an issue.
