### ISSUE TITLE
[ENHANCEMENT] Add fork instructions to Developer Setup Guide

### ISSUE THREAD

**Issue by rspacerr** [Bram-Hub/LEGUP#492]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

In the [Developer Setup Guide](https://github.com/Bram-Hub/Legup/wiki/Developer-Setup-Guide), include an instruction to uncheck the "only fork from default branch" checkbox which is on by default, since work should be done from the `dev` branch (I made this mistake).

### Describe the improvement you'd like

Something along the lines of:
> Uncheck the box saying to fork from the default branch only; dev work should be done on the `dev` branch or another branch

### Additional Context

![image](https://user-images.githubusercontent.com/61034617/222832595-9b3765f5-5c1e-49ba-aabb-e3ccf2b61bc6.png)

**Comment by VortiganOfficial** [comment]
Changes were made, mistakes fixed, and pictures updated
