### ISSUE TITLE
[BUG] <The Undo function in Solve Puzzle throws an Exception>

### ISSUE THREAD

**Issue by Mbijur** [Bram-Hub/LEGUP#499]
### Description

After a proof is written, pressing undo removes the previous action but throws an exception.

### Steps to Reproduce

1. Write a proof
2. Press Undo
3. See the Exception error thrown in the code.

### Expected Behavior

The program should undo the previous action without throwing the error.

### Screenshots

<img width="960" alt="Undo function" src="https://user-images.githubusercontent.com/122646363/226077678-dc67f185-115f-42dc-affe-3193c84d06c6.png">

**Comment by DavidColetta** [comment]
This does not seem to always be the case. I tried this with lightup and soduku, and undo worked correctly. I will test this under different circumstances to try and recreate this error. However, if I don't find anything I will mark this issue as resolved.

**Comment by charlestian23** [comment]
@Mbijur Would you be able to verify if this is a Sudoku only problem or if this problem is present for other puzzles? And if it is a Sudoku only problem, could you update the issue description?

**Comment by Mbijur** [comment]
Sure I’ll take a look at this later today.

Sincerely,
Maitri

On Mar 21, 2023, at 10:46 AM, Charles Tian ***@***.***> wrote:

﻿

@Mbijur<https://github.com/Mbijur> Would you be able to verify if this is a Sudoku only problem or if this problem is present for other puzzles? And if it is a Sudoku only problem, could you update the issue description?

**Comment by DavidColetta** [comment]
@charlestian23 I am still unable to replicate the error, even under the exact same circumstances as above.

**Comment by charlestian23** [comment]
Closing this since it seems to not be able to be replicated successfully.
