### ISSUE TITLE
changing the color blind preference after loading a puzzle doesnt change the rule images.

### ISSUE THREAD

**Issue by sparakala21** [Bram-Hub/LEGUP#502]
### Description

The colorblindness preference is supposed to change 3 things. the proof tree, the grid view and the rule images. If you open a puzzle and then change the preference, it will change the colors for the proof tree, and the grid view but not the images. the images only get reloaded when the preference is set before the puzzle is loaded.
if you need any info on how the colorblind preference works let me know.

### Steps to Reproduce

open legup
make sure that deuteranomaly is off.
load a puzzle 
check deuteranomaly on.

### Expected Behavior

the images should change

**Comment by N-Desmarais** [comment]
@sparakala21 take a look at what I've done here. This code all works, but might not necessarily be in the correct place. The reference to the RulesFrame withing the PreferencesDialog is not 100% best practices, an event handling approach would be better but the class structure of this project is so tangled I couldn't figure it out :/
