### ISSUE TITLE
[BUG] Tree Tent puzzle editor does not work

### ISSUE THREAD

**Issue by charlestian23** [Bram-Hub/LEGUP#503]
### Description

Despite being one of the puzzles that is marked as completed, Tree Tent does not fully function in the puzzle editor. Some functions are just not implemented.

### Steps to Reproduce

1. Open LEGUP
2. Click on "Create Puzzle"
3. Select Tree Tent and give any valid dimensions
4. Attempt to create a puzzle and notice that it does not work

### Expected Behavior

The Tree Tent puzzle editor should work as intended, just like Nurikabe.

### Additional Context

This issue is intended to be worked on by multiple people, who can reference Nurikabe for how to finish implementing the Tree Tent puzzle editor.

**Comment by jac-oblong** [comment]
fixed by #692
