### ISSUE TITLE
Documentation fix

### ISSUE THREAD

**Issue by Mbijur** [Bram-Hub/LEGUP#516]
I removed the flag <image> in the documentation because it kept giving an error, but it would be preferred if anyone can find out how it can work properly.
![image](https://user-images.githubusercontent.com/122646363/229237689-b9c5451d-f0ea-4280-9ec2-2368eeafed44.png)

**Comment by 25tallurich** [comment]
Can you expand on what flags you mean?

**Comment by Mbijur** [comment]
The <image> flag around the word visible.

**Comment by charlestian23** [comment]
Closing this since as far as I can tell, these XML-like tags don't work in Java comments.
