### ISSUE TITLE
[ENHANCEMENT] Keep file path in history

### ISSUE THREAD

**Issue by Bram28** [Bram-Hub/LEGUP#548]
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

I have all student work in one main folder, but when I am opening up multiple solution files, I have to keep navigating back to that main folder where all the student work is.

### Describe the improvement you'd like

When opening a file, I would like the file editor to open up at the same folder as the last file I opened up.

**Comment by hansongu123** [comment]
Closed by #562
