### ISSUE TITLE
[BUG] Interplay contradiction rule and modifying board

### ISSUE THREAD

**Issue by Bram28** [Bram-Hub/LEGUP#551]
### Description

If you use a contradiction rule, you should of course not be able to modify the board at thew same time. But currently LEGUP allows this ... leading to mistakes. 

### Steps to Reproduce

OK, let's start with a blank board, and immediately try a contradiction rule:

![image](https://github.com/Bram-Hub/LEGUP/assets/2414519/9df6e4ff-9cff-4d91-ad3e-d2c3ce0a42c3)

LEGUP correctly indicates that my use of the contradiction rule is incorrect. So far so good.

Now let's go back to the transition, and add two lightbulbs to the board:

![image](https://github.com/Bram-Hub/LEGUP/assets/2414519/d0e0c097-f8d1-43ea-9316-660e1663ea7e)

Oops! This should of course not happen.  The fundamental mistake is of course that I was able to make changes to the board in the first place during the transition that points to a contradiction rule.  If a contradiction rule is used, I should not also be able to make a change to the board.

By the way, what if we first make changes to the board (which of course I *should* be able to do, and then select a contradiction rule? Then it looks like this:

![image](https://github.com/Bram-Hub/LEGUP/assets/2414519/252efed0-269a-4038-a012-b058de0eb15b)

Well, at least the rule does not check out ... but I still have two lightbulbs being placed on the board as part of a transition that points to a contradiction rule.  Note that when I go back to the starting board state, and then go back to the transition, it looks like this:

![image](https://github.com/Bram-Hub/LEGUP/assets/2414519/d08857af-6cdb-4fb2-bd82-bb89f0f081ee)

OK, so the lightbulbs are no longer considered part of the transition ... but it's too late: we should never have allowed to have changes to the  board and a contradiction rule as part of the same transition!

### Expected Behavior

Here is what I propose:  when the user makes a change to the board, then the user will simply not be able to select a contradiction rule ... a warning should appear to that effect.  And when a transition already points to a contradiction rule, the user should not be able to make any changes to the board as part of that transition (again, maybe a warning will appear as soon as the user tries to make a change to the board as part of a contradiction rule transition)

**Comment by charlestian23** [comment]
@Chase-Grajeda This issue gets closed with #649, right?

**Comment by Chase-Grajeda** [comment]
Yup, #649 's changes fixed this bug. Closing
