### ISSUE TITLE
[BUG] Nurikabe Surround Region

### ISSUE THREAD

**Issue by Bram28** [Bram-Hub/LEGUP#553]
### Description

Nurikabe's Surround Region Direct rule seems to work as follows: a square should be made black if making it white would cause some region with a number to be greater than that number. That intuitively makes sense ... but also leads to a counterintuitive result ... which I think demands a change to how this rule is implemented

### Steps to Reproduce

Consider that the Siurround Region checks out in the situation below:

![image](https://github.com/Bram-Hub/LEGUP/assets/2414519/46d29f05-e9c7-4544-ba45-f154449fdead)

At first sight, the blacks around the 1 makes sense, but the blacks next to the 2 do not. However, the way the rule is implemented, it does work in the sense that if those squares next to the 2 are made white, then the 2 region becomes too big.

Likewise, the rule currently checks out here:

![image](https://github.com/Bram-Hub/LEGUP/assets/2414519/de79a0de-c2a8-4ac6-9959-cb25300e557f)

Again, it checks out because making the indicated square white would me the 1 region too big .... but it is of course *already* too big!  So it is really weird to think of this as 'surrounding a completed region'

Still, this is counterintuitive: the way we typically think about the Surround Region is when the whole region is of exactly the right size, and then we add its borders.  

I think we should implement the Surround Region accordingly

### Expected Behavior

Let's change the Surround Region rule in such a way that it only deals with regions that are of the exact right size as the number inside of it.  If we place a black next to a region that is either too big or too small, the rule will simply not check out.

Note that in the first scenario above, we can use the Black Between Regions rule.  And in the second scenario, the user will simply have to realize that there is a contradiction on the board and close the branch.

By the way, in the scenario below, I think it *is* ok that the Surround Region checks out:

![image](https://github.com/Bram-Hub/LEGUP/assets/2414519/9c8d29e7-6aa0-48c1-99ac-5573f88d5dec)

Yes, there is clearly a contradiction here, but it is true that the 3 region is of exactly the right size ... and if the user is just blind to the 4 (I suppose this would be somewhat more likely if we're dealing with *really* big region with the numbers far apart), then it's understandable that the user just wants to surround the completed 3.  So, the rule for Surround Region is that you can place blacks next to any white region that has the exact size as at least one of the numbers occurring in that region.

Also note that this means that we can no longer implement the Surround region merely as a derived rule on the basis of Black or White case rule together with Too Many Spaces contradiction rule (which is probably how it is currently implemented). Oh well.

Finally, let's rename the rule to 'Surround Completed Region'

**Comment by Chase-Grajeda** [comment]
Test file for debugging
[69495.zip](https://github.com/Bram-Hub/LEGUP/files/12899199/69495.zip)

**Comment by cadogs** [comment]
Merged closing
