### ISSUE TITLE
[BUG] Skyscrapers: content of cells goes only up to 2

### ISSUE THREAD

**Issue by Bram28** [Bram-Hub/LEGUP#579]
### Description

When cycling through the possible contents of a square in Skyscrapers, it only cycles up to 2 ... even though the board is 4x4 and so should cycle up to 4

### Steps to Reproduce

Open skyscrapers puzzle, and cycle through contents of some square.

### Expected Behavior

It should cycle up to the width = height of board

**Comment by Chase-Grajeda** [comment]
Closed by #618
