### ISSUE TITLE
[BUG] Able to change TreeTent goals

### ISSUE THREAD

**Issue by Kevin-771** [Bram-Hub/LEGUP#623]
### Description

While solving a TreeTent puzzle, we are able to change the horizontal goals of the puzzle.

### Steps to Reproduce

1. Open a Tree Tent Puzzle In "Solve Puzzle" mode
2. Click on the numbers on the right side of the board
3. Notice that you are able to change the numbers in the proof

### Expected Behavior

You should NOT be able to change the numbers that determine the number of tents in a row

### Screenshots

Before:
![image](https://github.com/Bram-Hub/LEGUP/assets/70790256/4ffbd60d-c82c-46fd-b4da-c55a79aff211)
After:
![image](https://github.com/Bram-Hub/LEGUP/assets/70790256/49882810-7e76-4801-a6ab-57e9011ef6fb)

### Puzzle Files

Any TreeTent puzzle file

**Comment by charlestian23** [comment]
Seems to be fixed on latest version of LEGUP, so closing this issue.
