### ISSUE TITLE
[BUG] Going back to transition with contradiction rule should not allow changes to board

### ISSUE THREAD

**Issue by Bram28** [Bram-Hub/LEGUP#624]
### Description

When you have applied a contradiction rule, and then go back to that transition, LEGUP allows you to change the board (and as a result the rule might even check out when it shouldn't!) ... but that is not allowed ... you should *never* be able to change the board *and* select a contradiction rule as part of the same transition.

### Steps to Reproduce

First get to this point:

![image](https://github.com/Bram-Hub/LEGUP/assets/2414519/c7f913b2-7462-4ce9-8ba4-79bc0fa2d864)

Now select the 'Cannot Light a Cell' Contradiction rule:

![image](https://github.com/Bram-Hub/LEGUP/assets/2414519/c3b30c1b-9cc7-4120-a309-b0ba3754c18f)

Notice the rule does not check out ... which it correct: there is no such contradiction here!

OK, but now make the square above the 2 empty, and you get:

![image](https://github.com/Bram-Hub/LEGUP/assets/2414519/1b9b410e-fcbd-44b7-98f9-cf3facc0bf83)

And sure, the is a contradiction on the board as shown ... but of course you should not have been able to make a change to the board when the transition is a contradiction rule!  Also note that after that initial board you *first* make that square empty, and *then* select the contradiction rule, the change to the board gets throw out (I suppose that is LEGUP's way of making sure that you cannot make board changes and select a contradiction rule) .. but of course you should nont be able to make board changes afterwards either.

### Expected Behavior

The board should not be modifiable during a transition that has a contradiction rule.

**Comment by Chase-Grajeda** [comment]
[buggyfile.zip](https://github.com/Bram-Hub/LEGUP/files/12796892/buggyfile.zip)

**Comment by Chase-Grajeda** [comment]
Attached is a file that can be used to test the implementation. The board from the yellow (non-contradictory) branch should be modifiable when clicking on the transition. The board from the red (contradictory) branch should NOT be modifiable when clicking on the transition.

[testfile.zip](https://github.com/Bram-Hub/LEGUP/files/12862237/testfile.zip)

**Comment by Chase-Grajeda** [comment]
Closed with merge
