### ISSUE TITLE
[BUG] Atomic Rule returns TRUE on Empty Cell

### ISSUE THREAD

**Issue by Chase-Grajeda** [Bram-Hub/LEGUP#679]
### Description

When applying the Atomic direct rule, the proof tree will incorrectly validate the board if the transition is edited and set to empty. This most likely comes from an oversight in the corresponding checkRuleRaw(). While this doesn't affect the puzzle completion very much, it is an error that should be cleared up

### Steps to Reproduce

1. Launch LEGUP and load a STT file (one is provided)
2. Find an atom that hasn't been evaluated yet (not green or red) and set it to green
3. Evaluate the board by applying the Atomic Rule in the Direct Rules folder
4. You should now notice the evaluation returns FALSE in the proof tree
5. Select previous transition and set the edited atom to UNKNOWN (not green or red)
6. You should now notice the board evaluation returns TRUE in the proof tree, which is erroneous

### Expected Behavior

When applying an atomic rule on an empty cell, or a cell that has type UNKNOWN, it should be evaluated as FALSE (red) on the proof tree

### Puzzle Files

[Heuveln_01.zip](https://github.com/Bram-Hub/LEGUP/files/13254725/Heuveln_01.zip)

**Comment by charlestian23** [comment]
Seems to have been fixed, closing.
