### ISSUE TITLE
Short Truth-Table: Enhancement/Feature: Truth-values specified in puzzle file

### ISSUE THREAD

**Issue by Bram28** [Bram-Hub/LEGUP#74]
Right now, the short truth-table puzzle assumes that the input is a bunch of statements, and that these statements reflect an argument, with the last one being the conclusion, and all others the premises. As such, LEGUP sets the last one to False (red), and the others to True (green).

Unfortunately, this makes it hard to explore other kinds of questions, such as "are these statements consistent?" (to check that, set all statements to True (green)), or "What kind of statement is this?" (if you work with that statement without setting any truth-value at all,, you may find it cannot be true (and hence its a contradiction), or that it cannot be false (so tautology), or that it can be eoither true or false (contingency).

So, to be handle to handle all those kinds of questions, we simply need to change it so that the input file can specify any kind of truth-value to any statement ... or specifies no truth-value at all.  So for each statement associate a value of true, false, or neither

**Comment by charlestian23** [comment]
This functionality seems to already be within LEGUP. See the attached file for reference. The `normal="true"` flag seems to automatically set files to have students check if statements are consistent. Removing that flag can allow files to be formatted to explore other kinds of questions.

[Heuveln_01_new.zip](https://github.com/Bram-Hub/LEGUP/files/10709321/Heuveln_01_new.zip)
